services:
  tritonserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nvcr.io/nvidia/tritonserver:22.06-py3
    image: nvcr.io/nvidian/sae/triton-server-demo:22-06-py3
