services:
  tritonserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=nvcr.io/nvidia/tritonserver:${BRANCH}-py3
    image: triton-server-demo:${BRANCH}-py3
