{
 "title": "Triton inference Server II",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Horizontal Pod Autoscalers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kube_horizontalpodautoscaler_status_current_replicas) by (horizontalpodautoscaler))"
    }
   ]
  },
  {
   "title": "Active Triton Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(nv_inference_count) by (instance))"
    }
   ]
  },
  {
   "title": "Compute Time by Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(nv_inference_compute_infer_duration_us[30s])) by (model) / 1000",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL) by (Hostname,gpu)",
     "legendFormat": "{{Hostname}} NVIDIA GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Power Utilization (kw)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE) by (Hostname,gpu)",
     "legendFormat": "{{Hostname}} NVIDIA GPU{{gpu}}"
    }
   ]
  },
  {
   "title": "Average Queue Time by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(nv_inference_queue_duration_us[30s])/(1+rate(nv_inference_request_success[30s]))) by (pod) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(nv_inference_request_success[30s]))",
     "legendFormat": "Success {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(nv_inference_request_failure[30s]))",
     "legendFormat": "Failure {{pod}}"
    }
   ]
  }
 ]
}